export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS'
export const GET_TWEETS_ERROR = 'GET_TWEETS_ERROR'
export const POST_TWEETS_SUCCESS = 'POST_TWEETS_SUCCESS'
export const POST_TWEETS_ERROR = 'POST_TWEETS_ERROR'

export const CAPTURE_TWEET_CONTENT = 'CAPTURE_TWEET_CONTENT'

export const LOADING = 'GET_TWEETS_LOADING'

export const SET_USER = 'SET_USER'
export const SET_USER_ERROR = 'SET_USER_ERROR'

export const SET_CHAR = 'SET_CHAR'
export const SET_DRAG = 'SET_DRAG'
export const SET_TASK = 'SET_TASK'
export const SET_IMAGE = 'SET_IMAGE'

export const DRAG_IMAGE_STATES = {
  ERROR: -1,
  NONE: 0,
  DRAG_OVER: 1,
  UPLOADING: 2,
  COMPLETE: 3,
}
