export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS'
export const GET_TWEETS_ERROR = 'GET_TWEETS_ERROR'
export const POST_TWEETS_SUCCESS = 'POST_TWEETS_SUCCESS'
export const POST_TWEETS_ERROR = 'POST_TWEETS_ERROR'

export const CAPTURE_TWEET_CONTENT = 'CAPTURE_TWEET_CONTENT'

export const LOADING = 'GET_TWEETS_LOADING'

export const SET_USER = 'SET_USER'
export const SET_USER_ERROR = 'SET_USER_ERROR'